# Generated by Django 2.2.6 on 2019-10-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bus',
        ),
        migrations.DeleteModel(
            name='driver',
        ),
        migrations.DeleteModel(
            name='route',
        ),
    ]
