# Generated by Django 2.2.6 on 2019-10-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0003_bus_driver_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='time_line',
            new_name='time',
        ),
        migrations.AddField(
            model_name='bus',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
