# Generated by Django 2.2.6 on 2019-10-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0005_bus_asigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='asigned_to',
        ),
    ]
