# Generated by Django 2.2.6 on 2019-10-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0006_remove_bus_asigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='asigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_routing.Driver'),
        ),
    ]
